language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"

sudo: required
dist: xenial

matrix:
    allow_failures:
        - python: "3.5"
        - python: "3.6"
        - python: "nightly"

env:
  global:
    - C_INCLUDE_PATH=/usr/lib/openmpi/include
    - WITH_CUDA: true
    - DEPLOY_DOCS_FOR_PYTHON: '3.8'
    - TRIGGER_DOCKER_FOR_PYTHON: '3.8'
    - SIMEX_VERBOSE=MPI:PYTHON

addons:
  apt:
    packages:
      - openmpi-bin
      - libopenmpi-dev
      - wget
      - libhdf5-dev
      - build-essential
      - libbz2-dev
      - libfftw3-dev
      - liblapack-dev
      - cmake
      - gfortran
      - unzip
      - cython3
      - sphinx-common
      - python3-sphinx
      - libgsl0-dev
      - llvm
      - nvidia-cuda-dev
      - nvidia-profiler
      - nvidia-cuda-toolkit

cache:
  apt: false
  directories:
    - $HOME/.cache/pip
    - $HOME/lib

# install git lfs
#   see https://github.com/travis-ci/travis-ci/issues/3634
before_install:
    - mkdir -p $HOME/bin
    - wget https://github.com/github/git-lfs/releases/download/v1.1.2/git-lfs-linux-amd64-1.1.2.tar.gz
    - tar xvfz git-lfs-linux-amd64-1.1.2.tar.gz
    - mv git-lfs-1.1.2/git-lfs $HOME/bin/git-lfs
    - export PATH=$PATH:$HOME/bin/
      # attempt to make py3.6 go through.
    - export Python_ROOT_DIR=$(dirname $(dirname $(which python)))
      #- bash $TRAVIS_BUILD_DIR/TravisCI/pyqt.sh ## only needed for python v<3.5

before_script:
  - python --version
  - python -c "import numpy as np; print( np.__version__ )"
  - python -c "import h5py as h5; print( h5.__version__ )"
  - ulimit -c unlimited
  - mpirun --version

script:
    #- wget ftp://ftp.wwpdb.org/pub/pdb/data/structures/divided/pdb/ni/pdb2nip.ent.gz
  - bash $TRAVIS_BUILD_DIR/TravisCI/build_and_test_simex.sh && bash $TRAVIS_BUILD_DIR/TravisCI/deploy_docs.sh
after_success:
  - bash $TRAVIS_BUILD_DIR/TravisCI/trigger_docker.sh
